baseurl = "/"
languageCode = "pt-br"
title = "Ramon Rodrigues"
theme = "hello-friend"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 3

description = "Site do Ramon Rodrigues"
keywords = "programação, python, rust, golang"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[author]
  name = "Ramon Rodrigues"

[[menu.main]]
    name = "Sobre"
    url = "/about/"
    weight = 1

[params]
    contentTypeName = "posts"
    defaultTheme = "dark"
    showReadingTime = false
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[params.logo]
    width = 50
    height = 50
    alt = "Logo"
    logoText = "ramon rodrigues"
    logoHomeLink = "/"
