baseurl = "/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"

title = "ramonrwx"
theme = "hello-friend"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 5

description = "Site do Ramon Rodrigues"
keywords = "programação, python, rust, golang"

enableEmoji = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "ramonrwx"

[[menu.main]]
  name = "Sobre"
  url = "/about/"
  weight = 1

[params]
	contentTypeName = "posts"
	defaultTheme = "dark"
	enableGlobalLanguageMenu = true
	showReadingTime = true
	highlightjsVersion = "9.12.0"
	highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
	highlightjsLang = ["rust", "yaml", "python", "go", "sh", "bash", "lua"]
	highlightjsTheme = "github"
	MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
	MathJaxVersion = "2.7.5"

[languages]
  [languages.pt-br]
    menuMore = "Mostrar mais"
    writtenBy = "por"
    readMore = "Ler mais"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Mais recentes"
    olderPosts = "Mais antigos"
    minuteReadingTime = "min de leitura"

[params.logo]
	width = 50
	height = 50
	alt = "Logo"
	logoText = "ramonrwx"
	logoHomeLink = "/"
